version: '3.9'
services:
  user_service:
    container_name: user_service
    build:
      context: ./userservice
      target: development
    env_file:
      - ./userservice/.env.dev.compose
    command: npm run start:dev
    volumes:
      - ./userservice:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4000:3000'
  event_service:
    container_name: event_service
    build:
      context: ./eventservice
      target: development
    env_file:
      - ./eventservice/.env.dev.compose
    command: npm run start:dev
    volumes:
      - ./eventservice:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4001:3000'
  post_service:
    container_name: post_service
    build:
      context: ./postservice
      target: development
    env_file:
      - ./postservice/.env.dev.compose
    command: npm run start:dev
    volumes:
      - ./postservice:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4002:3000'
  comment_service:
    container_name: comment_service
    build:
      context: ./commentservice
      target: development
    env_file:
      - ./commentservice/.env.dev.compose
    command: npm run start:dev
    volumes:
      - ./commentservice:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4003:3000'
  test_database:
    container_name: test_database
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db/local_postgres.init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

  nginx_load_balancer:
    container_name: loader_balancer
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'

  # rabbitmq:
  #   container_name: event_bus
  #   image: rabbitmq:3-management
  #   ports:
  #     - '8080:15672'
  #     - '5672:5672'
